import React, { createContext, useContext, useState } from 'react';

const vi = {
  // Header
  appName: 'Barrier Gen2',
  connect: 'KẾT NỐI',
  connected: 'ĐÃ KẾT NỐI',
  // Dash
  signalStatus: 'TRẠNG THÁI TÍN HIỆU',
  closeLimit: 'CLOSE\nLIMIT',
  openLimit: 'OPEN\nLIMIT',
  closeDecel: 'CLOSE\nDECEL',
  openDecel: 'OPEN\nDECEL',
  photoCell: 'PHOTO\nCELL',
  controls: 'ĐIỀU KHIỂN',
  power: 'NGUỒN',
  stop: 'DỪNG',
  close: 'ĐÓNG',
  open: 'MỞ',
  learningRemote: '📡  HỌC REMOTE',
  bmsData: 'DỮ LIỆU BMS',
  driverData: 'DỮ LIỆU DRIVER',
  quickSpeed: 'TỐC ĐỘ NHANH',
  closeSpeed: 'Tốc độ đóng cửa',
  openSpeed: 'Tốc độ mở cửa',
  send: 'GỬI',
  notConnected: 'Kết nối HC-05 để sử dụng điều khiển',
  cmdSent: '↑ Đã gửi lệnh: ',
  voltage: 'Điện áp',
  capacity: 'Dung lượng',
  current: 'Dòng điện',
  power2: 'Công suất',
  temp: 'Nhiệt độ',
  throttle: 'Throttle',
  firmware: 'Firmware',
  // Settings
  powerSettings: 'CÀI ĐẶT NGUỒN',
  motorSettings: 'CÀI ĐẶT MOTOR',
  speedSettings: 'CÀI ĐẶT TỐC ĐỘ',
  switchSettings: 'CÀI ĐẶT CÔNG TẮC',
  read: 'ĐỌC',
  write: 'GHI',
  powerType: 'Nguồn điện',
  voltageParam: 'Điện áp',
  soc: 'Dung lượng Pin',
  ovp: 'Bảo vệ quá áp',
  uvp: 'Bảo vệ thấp áp',
  ocp: 'Bảo vệ quá dòng',
  gearBox: 'Tỷ số hộp số',
  motorDir: 'Chiều quay',
  driverType: 'Loại Driver',
  cmdType: 'Kiểu lệnh',
  decelType: 'Kiểu giảm tốc',
  decelTime: 'Thời gian giảm tốc',
  photocellMode: 'Photocell mode',
  closeSpeedParam: 'Tốc độ đóng',
  openSpeedParam: 'Tốc độ mở',
  closeDecelSpeed: 'Giảm tốc đóng',
  openDecelSpeed: 'Giảm tốc mở',
  startCwSpeed: 'Khởi động CW',
  startCcwSpeed: 'Khởi động CCW',
  startCwTime: 'Thời gian CW',
  startCcwTime: 'Thời gian CCW',
  // App settings
  appInfo: 'THÔNG TIN ỨNG DỤNG',
  deviceInfo: 'THÔNG TIN THIẾT BỊ',
  displaySettings: 'CÀI ĐẶT HIỂN THỊ',
  darkMode: 'Chế độ tối (Dark Mode)',
  darkOn: '🌙 Đang dùng chế độ tối',
  darkOff: '☀️ Đang dùng chế độ sáng',
  language: 'NGÔN NGỮ',
  langVi: '🇻🇳 Tiếng Việt',
  langEn: '🇬🇧 English',
  system: 'HỆ THỐNG',
  resetFactory: '🔄  RESET VỀ MẶC ĐỊNH',
  mainLock: 'KHÓA MAIN',
  mainLockDesc: 'Khóa mainboard. Thiết bị sẽ bị vô hiệu hóa cho đến khi mở khóa. Sử dụng cẩn thận.',
  mainLockBtn: '🔐  MAIN LOCK',
  confirmLock: 'Xác nhận MAIN LOCK',
  confirmLockMsg: 'Bạn có chắc muốn khóa mainboard?\n\nThiết bị sẽ không hoạt động cho đến khi mở khóa.',
  confirmReset: 'Toàn bộ thông số sẽ về mặc định. Tiếp tục?',
  cancel: 'Hủy',
  confirm: 'XÁC NHẬN KHÓA',
  reset: 'Reset',
  notConnectedAlert: 'Chưa kết nối',
  connectFirst: 'Kết nối HC-05 để dùng tính năng này',
  battery: 'Pin',
  smps: 'SMPS',
  odometer: 'Odometer',
  mode: 'Mode',
  error: 'Lỗi',
  appVersion: 'Phiên bản',
  protocol: 'Giao thức',
  baudRate: 'Baud Rate',
};

const en = {
  appName: 'Barrier Gen2',
  connect: 'CONNECT',
  connected: 'CONNECTED',
  signalStatus: 'SIGNAL STATUS',
  closeLimit: 'CLOSE\nLIMIT',
  openLimit: 'OPEN\nLIMIT',
  closeDecel: 'CLOSE\nDECEL',
  openDecel: 'OPEN\nDECEL',
  photoCell: 'PHOTO\nCELL',
  controls: 'CONTROLS',
  power: 'POWER',
  stop: 'STOP',
  close: 'CLOSE',
  open: 'OPEN',
  learningRemote: '📡  LEARNING REMOTE',
  bmsData: 'BMS DATA',
  driverData: 'DRIVER DATA',
  quickSpeed: 'QUICK SPEED',
  closeSpeed: 'Close speed',
  openSpeed: 'Open speed',
  send: 'SEND',
  notConnected: 'Connect HC-05 to use controls',
  cmdSent: '↑ Command sent: ',
  voltage: 'Voltage',
  capacity: 'Capacity',
  current: 'Current',
  power2: 'Power',
  temp: 'Temp',
  throttle: 'Throttle',
  firmware: 'Firmware',
  powerSettings: 'POWER SETTINGS',
  motorSettings: 'MOTOR SETTINGS',
  speedSettings: 'SPEED SETTINGS',
  switchSettings: 'SWITCH SETTINGS',
  read: 'READ',
  write: 'WRITE',
  powerType: 'Power type',
  voltageParam: 'Voltage',
  soc: 'Battery SOC',
  ovp: 'Overvoltage protect',
  uvp: 'Undervoltage protect',
  ocp: 'Overcurrent protect',
  gearBox: 'Gear box ratio',
  motorDir: 'Motor direction',
  driverType: 'Driver type',
  cmdType: 'Command type',
  decelType: 'Decel run type',
  decelTime: 'Decel run time',
  photocellMode: 'Photocell mode',
  closeSpeedParam: 'Close speed',
  openSpeedParam: 'Open speed',
  closeDecelSpeed: 'Close decel speed',
  openDecelSpeed: 'Open decel speed',
  startCwSpeed: 'Start CW speed',
  startCcwSpeed: 'Start CCW speed',
  startCwTime: 'Start CW time',
  startCcwTime: 'Start CCW time',
  appInfo: 'APP INFORMATION',
  deviceInfo: 'DEVICE INFORMATION',
  displaySettings: 'DISPLAY SETTINGS',
  darkMode: 'Dark Mode',
  darkOn: '🌙 Dark mode active',
  darkOff: '☀️ Light mode active',
  language: 'LANGUAGE',
  langVi: '🇻🇳 Tiếng Việt',
  langEn: '🇬🇧 English',
  system: 'SYSTEM',
  resetFactory: '🔄  RESET TO FACTORY',
  mainLock: 'MAIN LOCK',
  mainLockDesc: 'Lock the mainboard. Device will be disabled until unlocked. Use with caution.',
  mainLockBtn: '🔐  MAIN LOCK',
  confirmLock: 'Confirm MAIN LOCK',
  confirmLockMsg: 'Are you sure you want to lock the mainboard?\n\nDevice will not work until unlocked.',
  confirmReset: 'All parameters will be reset to defaults. Continue?',
  cancel: 'Cancel',
  confirm: 'CONFIRM LOCK',
  reset: 'Reset',
  notConnectedAlert: 'Not connected',
  connectFirst: 'Connect HC-05 to use this feature',
  battery: 'Battery',
  smps: 'SMPS',
  odometer: 'Odometer',
  mode: 'Mode',
  error: 'Error',
  appVersion: 'Version',
  protocol: 'Protocol',
  baudRate: 'Baud Rate',
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('vi');
  const t = lang === 'vi' ? vi : en;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
